-- Generated by Oracle SQL Developer Data Modeler 4.0.0.825
--   at:        2013-12-01 11:20:57 BRST
--   site:      Oracle Database 11g
--   type:      Oracle Database 11g




CREATE TABLE biblioteca.autor
  (
    id_autor   NUMBER NOT NULL ,
    nome_autor VARCHAR2 (50) NOT NULL
  ) ;
COMMENT ON TABLE biblioteca.autor
IS
  'Tabela autor
----Destinada a armazenar as inforamcoes referentes a autores' ;
  ALTER TABLE biblioteca.autor ADD CONSTRAINT autor_PK PRIMARY KEY ( id_autor ) ;

CREATE TABLE biblioteca.bibliotecario_pessoa
  (
    id_pessoa                   NUMBER NOT NULL ,
    nome_completo_pessoa        VARCHAR2 (50) ,
    cpf_pessoa                  VARCHAR2 (11) ,
    rg_pessoa                   VARCHAR2 (11) ,
    endrec_pessoa               VARCHAR2 (50) ,
    fone_pessoa                 VARCHAR2 (13) ,
    email_pessoa                VARCHAR2 (30) ,
    data_nascimento_pessoa      VARCHAR2 (8) ,
    data_admissao_bibliotecario VARCHAR2 (8) ,
    crb_bibliotecario           VARCHAR2 (13) NOT NULL ,
    salario_bibliotecario       NUMBER
  ) ;
COMMENT ON TABLE biblioteca.bibliotecario_pessoa
IS
  'Tabela bibliotecario / Pessoa
----Destinada a armazenar as inforamcoes referentes aos bibliotecarios cadastrados
----Contem tambem informacoes relativas a pessoa do bibliotecario' ;
  ALTER TABLE biblioteca.bibliotecario_pessoa ADD CONSTRAINT bibliotecario_PK PRIMARY KEY ( id_pessoa ) ;

CREATE TABLE biblioteca.editora
  (
    id_editora       NUMBER NOT NULL ,
    nome_editora     VARCHAR2 (50) ,
    cnpj_editora     VARCHAR2 (14) ,
    endereco_editora VARCHAR2 (50) ,
    site_editora     VARCHAR2 (40) ,
    email_editora    VARCHAR2 (50) ,
    fone_editora     VARCHAR2 (11) ,
    observacoes      VARCHAR2 (200)
  ) ;
COMMENT ON TABLE biblioteca.editora
IS
  'Tabela editora
----Destinada a armazenar as inforamcoes referentes a editoras' ;
  ALTER TABLE biblioteca.editora ADD CONSTRAINT editora_PK PRIMARY KEY ( id_editora ) ;

CREATE TABLE biblioteca.genero
  (
    id_genero        NUMBER NOT NULL ,
    nome_genero      VARCHAR2 (50) ,
    definicao_genero VARCHAR2 (50)
  ) ;
COMMENT ON TABLE biblioteca.genero
IS
  'Tabela genero
----Destinada a armazenar as informacoes dos generos cadastrados' ;
  ALTER TABLE biblioteca.genero ADD CONSTRAINT genero_PK PRIMARY KEY ( id_genero ) ;

CREATE TABLE biblioteca.livro
  (
    id_livro     NUMBER NOT NULL ,
    titulo_livro VARCHAR2 (50) ,
    edicao       VARCHAR2 (15) ,
    data_edicao  VARCHAR2 (8),
    ISBN         VARCHAR2 (13) ,
    id_autor     NUMBER NOT NULL ,
    id_editora   NUMBER NOT NULL ,
    id_genero    NUMBER NOT NULL
  ) ;
COMMENT ON TABLE biblioteca.livro
IS
  'Tabela livro
----Destinada a armazenar as inforamcoes referentes aos livros cadastrados' ;
  ALTER TABLE biblioteca.livro ADD CONSTRAINT livro_PK PRIMARY KEY ( id_livro ) ;

CREATE TABLE biblioteca.movimentacao
  (
    id_usuario      NUMBER NOT NULL ,
    id_volume       NUMBER NOT NULL ,
    id_movimentacao NUMBER NOT NULL
  ) ;
ALTER TABLE biblioteca.movimentacao ADD CONSTRAINT movimentacao_PK PRIMARY KEY ( id_movimentacao, id_usuario, id_volume ) ;

CREATE TABLE biblioteca.preferencias
  (
    id_usuario NUMBER NOT NULL ,
    id_genero  NUMBER NOT NULL
  ) ;
ALTER TABLE biblioteca.preferencias ADD CONSTRAINT preferencias_PK PRIMARY KEY ( id_usuario, id_genero ) ;

CREATE TABLE biblioteca.reservaLivro
  (
    id_usuario NUMBER NOT NULL ,
    id_volume  NUMBER NOT NULL ,
    id_reserva NUMBER NOT NULL
  ) ;
COMMENT ON TABLE biblioteca.reservaLivro
IS
  'Tabela reserva
----Destinada a armazenar as inforamcoes referentes aos usuarios  e volumes de livros durante um pedido de reserva' ;
  ALTER TABLE biblioteca.reservaLivro ADD CONSTRAINT reservaLivro_PK PRIMARY KEY ( id_reserva, id_usuario, id_volume ) ;

CREATE TABLE biblioteca.usuario_pessoa
  (
    id_pessoa              NUMBER NOT NULL ,
    nome_completo_pessoa   VARCHAR2 (50) ,
    cpf_pessoa             VARCHAR2 (11) ,
    rg_pessoa              VARCHAR2 (11) ,
    endereco_pessoa        VARCHAR2 (50) ,
    fone_pessoa            VARCHAR2 (13) ,
    email_pessoa           VARCHAR2 (30) ,
    data_nascimento_pessoa VARCHAR2 (8) ,
    data_cadastro_usuario  VARCHAR2 (8)
  ) ;
COMMENT ON TABLE biblioteca.usuario_pessoa
IS
  'Tabela usuario / Pessoa
----Destinada a armazenar as inforamcoes referentes aos usuarios cadastrados
----Contem tambem informacoes relativas a pessoa do usuario' ;
  ALTER TABLE biblioteca.usuario_pessoa ADD CONSTRAINT usuario_pessoa_PK PRIMARY KEY ( id_pessoa ) ;

CREATE TABLE biblioteca.volume
  (
    id_livro           NUMBER NOT NULL ,
    id_volume          NUMBER NOT NULL ,
    conservacao_volume CHAR (1)
  ) ;
COMMENT ON TABLE biblioteca.volume
IS
  'Tabela volume
----Destinada a armazenar as inforamcoes referentes aos volumes de cada livro cadastrado' ;
  ALTER TABLE biblioteca.volume ADD CONSTRAINT volume_PK PRIMARY KEY ( id_volume ) ;

ALTER TABLE biblioteca.preferencias ADD CONSTRAINT TABLE_9_genero_FK FOREIGN KEY ( id_genero ) REFERENCES biblioteca.genero ( id_genero ) ;

ALTER TABLE biblioteca.livro ADD CONSTRAINT livro_autor_FK FOREIGN KEY ( id_autor ) REFERENCES biblioteca.autor ( id_autor ) ;

ALTER TABLE biblioteca.livro ADD CONSTRAINT livro_editora_FK FOREIGN KEY ( id_editora ) REFERENCES biblioteca.editora ( id_editora ) ;

ALTER TABLE biblioteca.livro ADD CONSTRAINT livro_genero_FK FOREIGN KEY ( id_genero ) REFERENCES biblioteca.genero ( id_genero ) ;

ALTER TABLE biblioteca.movimentacao ADD CONSTRAINT movimentacao_usuario_pessoa_FK FOREIGN KEY ( id_usuario ) REFERENCES biblioteca.usuario_pessoa ( id_pessoa ) ;

ALTER TABLE biblioteca.movimentacao ADD CONSTRAINT movimentacao_volume_FK FOREIGN KEY ( id_volume ) REFERENCES biblioteca.volume ( id_volume ) ;

ALTER TABLE biblioteca.preferencias ADD CONSTRAINT preferencias_usuario_pessoa_FK FOREIGN KEY ( id_usuario ) REFERENCES biblioteca.usuario_pessoa ( id_pessoa ) ;

ALTER TABLE biblioteca.reservaLivro ADD CONSTRAINT reservaLivro_usuario_pessoa_FK FOREIGN KEY ( id_usuario ) REFERENCES biblioteca.usuario_pessoa ( id_pessoa ) ;

ALTER TABLE biblioteca.reservaLivro ADD CONSTRAINT reservaLivro_volume_FK FOREIGN KEY ( id_volume ) REFERENCES biblioteca.volume ( id_volume ) ;

ALTER TABLE biblioteca.volume ADD CONSTRAINT volume_livro_FK FOREIGN KEY ( id_livro ) REFERENCES biblioteca.livro ( id_livro ) ;


-- Oracle SQL Developer Data Modeler Summary Report: 
-- 
-- CREATE TABLE                            10
-- CREATE INDEX                             0
-- ALTER TABLE                             20
-- CREATE VIEW                              0
-- CREATE PACKAGE                           0
-- CREATE PACKAGE BODY                      0
-- CREATE PROCEDURE                         0
-- CREATE FUNCTION                          0
-- CREATE TRIGGER                           0
-- ALTER TRIGGER                            0
-- CREATE COLLECTION TYPE                   0
-- CREATE STRUCTURED TYPE                   0
-- CREATE STRUCTURED TYPE BODY              0
-- CREATE CLUSTER                           0
-- CREATE CONTEXT                           0
-- CREATE DATABASE                          0
-- CREATE DIMENSION                         0
-- CREATE DIRECTORY                         0
-- CREATE DISK GROUP                        0
-- CREATE ROLE                              0
-- CREATE ROLLBACK SEGMENT                  0
-- CREATE SEQUENCE                          0
-- CREATE MATERIALIZED VIEW                 0
-- CREATE SYNONYM                           0
-- CREATE TABLESPACE                        0
-- CREATE USER                              0
-- 
-- DROP TABLESPACE                          0
-- DROP DATABASE                            0
-- 
-- REDACTION POLICY                         0
-- 
-- ERRORS                                   0
-- WARNINGS                                 0
